sections:
  main:
    display: Main
    fields:
      -
        handle: pages_links
        field:
          collapse: false
          previews: true
          sets:
            page:
              display: Page
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: link_to_page
                  field:
                    display: 'Link to page'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: is_anchor
                  field:
                    default: false
                    display: 'Is anchor'
                    type: toggle
                    icon: toggle
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: parent_link
                  field:
                    display: 'Parent link'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    if:
                      is_anchor: 'equals true'
          display: 'Pages links'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: button_text
        field:
          input_type: text
          antlers: false
          display: 'Button text'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: button_link
        field:
          display: 'Button link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
